routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
/**
 * AUTHENTICATION
 */
Route::group(['prefix' => '/', 'as' => 'auth.'], function () {

    /**
     * Middleware Guest
     */
    Route::middleware(['guest'])->group(function () {
        // Login
        Route::get('/login', 'Auth\LoginController@showLoginForm')->name('login.form');
        Route::post('/login', 'Auth\LoginController@login')->name('login.post');

        // Forgot
        Route::get('/forgot', 'Auth\ForgotPasswordController@index')->name('forgot');
        Route::post('/forgot', 'Auth\ForgotPasswordController@sendEmail')->name('forgot.send');
        Route::get('/forgot/verify/{token}', 'Auth\ForgotPasswordController@verifyMail')->name('forgot.verify');
    });
    Route::middleware(['auth'])->group(function () {
        Route::get('/register/{accountno?}/{leg?}', 'Auth\RegisterController@showRegistrationForm')->name('register.form');
        Route::post('/register', 'Auth\RegisterController@register')->name('register.post');
    });

    // Logout
    Route::post('/logout', 'Auth\LoginController@logout')->name('logout')->middleware('auth');
});


/**
 * FRONT PAGE
 */
Route::group(['prefix' => '/', 'as' => 'front.'], function () {

    // Home
    Route::get('/', function () {
        return view('front.home.index');
    })->name('home');

    // Investment
    Route::get('/investment', function () {
        return view('front.investment.index');
    })->name('investment');

    // About
    Route::get('/about', function () {
        return view('front.about.index');
    })->name('about');

    // Faq
    Route::get('/faq', function () {
        return view('front.faq.index');
    })->name('faq');

    // Contact
    Route::get('/contact', function () {
        return view('front.contact.index');
    })->name('contact');

    // Tems
    Route::get('/tems', function () {
        return view('front.tems.index');
    })->name('tems');
});

/**
 * Auth Middleware Group
 */
Route::middleware(['auth'])->group(function () {
    /**
     * DASHBOARD PAGE
     */
    Route::group(['prefix' => '/dashboard', 'as' => 'dashboard.','middleware' => 'user'], function () {

        // Home
        Route::get('/', 'DashBoard\HomeController@index')->name('home');

        // Wallet
        Route::get('/wallet', 'DashBoard\WalletController@index')->name('wallet');
        Route::post('/wallet', 'DashBoard\WalletController@handleWithdraw')->name('wallet');
        Route::get('/withdraw', 'DashBoard\WalletController@getWithdraw')->name('withdraw');
        Route::post('/withdraw', 'DashBoard\WalletController@postWithdraw')->name('withdraw');

        // Wallet
        Route::get('/referrals', 'DashBoard\ReferralController@index')->name('referrals');

        // Binary
        Route::get('/binary/{accountno?}', 'DashBoard\BinaryController@index')->name('binary');

        // Transactions
        Route::get('/transactions', 'DashBoard\TransactionController@index')->name('transactions');

        Route::get('/deposit', 'DashBoard\DepositController@deposit')->name('deposit');
        Route::post('/deposit', 'DashBoard\DepositController@postDeposit')->name('deposit');

        // Commission
        Route::get('/commission', 'DashBoard\CommissionController@index')->name('commission.index');
        Route::post('/commission/email', 'DashBoard\CommissionController@handleEmail')->name('commission.email');
        Route::get('/commission/withdraw', 'DashBoard\CommissionController@getCommission')->name('commission');
        Route::post('/commission/withdraw', 'DashBoard\CommissionController@postCommission')->name('commission');
        Route::get('/commission/binary', 'DashBoard\CommissionController@getBinary')->name('binary.commission');
        Route::post('/commission/binary', 'DashBoard\CommissionController@postBinary')->name('binary.commission');
        Route::get('/monthly/withdraw', 'DashBoard\CommissionController@getMonthly')->name('monthly');
        Route::post('/monthly/withdraw', 'DashBoard\CommissionController@postMonthly')->name('monthly');

        // User
        Route::group(['prefix' => '/user', 'as' => 'user.'], function () {
            Route::get('/overview', 'DashBoard\UserController@overview')->name('overview');

            // Profile
            Route::get('/profile', 'DashBoard\UserController@profile')->name('profile');
            Route::put('/profile', 'DashBoard\UserController@updateProfile')->name('profile.update');
            Route::put('/profile/password', 'DashBoard\UserController@updatePassword')->name('profile.password');
        });

        // Contact
        Route::get('/contact', 'DashBoard\ContactController@index')->name('contact');
        Route::post('/contact', 'DashBoard\ContactController@sendMail')->name('contact.send');

        // Calendar
        Route::get('/calendar', function () {
            return view('dashboard.calendar.index');
        })->name('calendar');

    });

    /**
     * ADMIN PAGE
     */
    Route::group(['prefix' => '/admin', 'as' => 'admin.','middleware' => 'admin'], function () {
        // Home
        Route::get('/', function () {
            return view('admin.home.index');
        })->name('home');

        Route::get('/kickdeposit', 'Admin\DepositController@deposit')->name('kickdeposit');
        Route::post('/kickdeposit', 'Admin\DepositController@postDeposit')->name('kickdeposit');

        Route::get('/countprofit/monthly', 'Admin\ProfitMonthlyController@index')->name('countprofit');

        // Pay
        Route::group(['prefix' => '/pay', 'as' => 'pay.'], function () {

            Route::get('/profit', 'Admin\PaymentController@profit')->name('profit');
            Route::post('/profit/{id}', 'Admin\PaymentController@withdrawProfit')->name('profit.withdraw');

            Route::get('/interest', 'Admin\PaymentController@interest')->name('interest');
            Route::post('/interest/{id}', 'Admin\PaymentController@payInterest')->name('interest.withdraw');

            Route::get('/wallet', 'Admin\PaymentController@wallet')->name('wallet');
            Route::post('/wallet/{id}', 'Admin\PaymentController@withdrawWallet')->name('wallet.withdraw');
        });

        Route::get('/binary', 'Admin\BinaryController@index')->name('binary');
        Route::post('/binary/{id}', 'Admin\BinaryController@payment')->name('binary.payment');

        // ADmin
        Route::group(['prefix' => '/user', 'as' => 'user.'], function () {
            Route::get('/overview', 'Admin\UserController@overview')->name('overview');

            // Profile
            Route::get('/profile', 'Admin\UserController@profile')->name('profile');
            Route::put('/profile', 'Admin\UserController@updateProfile')->name('profile.update');
            Route::put('/profile/password', 'Admin\UserController@updatePassword')->name('profile.password');
        });

        Route::get('/transfer', 'Admin\TransferController@getTransfer')->name('transfer');
        Route::post('/transfer', 'Admin\TransferController@postTransfer')->name('transfer');
    });
});

app/Http/Controllers/DashBoard/BinaryController.php
<?php

namespace App\Http\Controllers\DashBoard;

use App\Business\BinaryDownlineBusiness;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Auth;

class BinaryController extends Controller
{
    /**
     * Instance $binaryDownlineBusiness
     *
     * @var BinaryDownlineBusiness
     */
    protected $binaryDownlineBusiness;

    /**
     * BinaryController constructor.
     *
     * @param BinaryDownlineBusiness $binaryDownlineBusiness
     */
    public function __construct(BinaryDownlineBusiness $binaryDownlineBusiness)
    {
        $this->binaryDownlineBusiness = $binaryDownlineBusiness;
    }

    public function index($accountno = null)
    {

        // Get Current User Id by Request
        if (is_null($accountno)) {
            $accountno = Auth::user()->accountno;
        }

        // Get Current Users List;
        $curUsers = $this->binaryDownlineBusiness->where('accountno', $accountno)->get();

        // Level of Tree
        $level = 4;

        return view('dashboard.binary.index', compact('curUsers', 'level'));

    }
}

app/Http/Controllers/DashBoard/ContactController.php
<?php

namespace App\Http\Controllers\DashBoard;

use App\Http\Controllers\Controller;
use App\Http\Requests\DashBoard\ContactRequest;
use App\Mail\ContactEmail;

class ContactController extends Controller
{
    public function index()
    {
        return view('dashboard.contact.index');
    }

    /**
     * Send Mail Method
     *
     * @param ContactRequest $request
     *
     * @return \Response
     */
    public function sendMail(ContactRequest $request)
    {
        try {
            $contactEmail = collect([
                'name'    => $request->input('name'),
                'email'   => $request->input('email'),
                'ccno'    => $request->input('ccno'),
                'message' => $request->input('message')
            ]);
            \Mail::to(env('MAIL_USERNAME'))->send(new ContactEmail($contactEmail));

            return redirect()->route('dashboard.contact')->with([
                'status'  => 'success',
                'message' => 'Your message was sent!!!'
            ]);
        } catch (\Exception $e) {
            \Log::error('DashBoard\ContactController::sendMail : ' . $e->getMessage());

            return redirect()->route('dashboard.contact')->with([
                'status'  => 'danger',
                'message' => 'Something went wrong!!!!'
            ]);
        }
    }
}

app/Http/Controllers/DashBoard/DepositController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Business\BinaryDownlineBusiness;
use App\Business\DepositBusiness;
use App\Business\WalletBusiness;
use App\Http\Controllers\Controller;
use DB;
use Exception;
use Illuminate\Http\Request;
use Auth;

class DepositController extends Controller
{

    private $_deposit;
    private $_wallet;
    private $_binary;

    public function __construct(DepositBusiness $deposit, WalletBusiness $wallet, BinaryDownlineBusiness $binary)
    {
        $this->_deposit = $deposit;
        $this->_wallet = $wallet;
        $this->_binary = $binary;
    }

    public function deposit()
    {
                 
        $balance = \LaraBlockIo::getAddressesBalanceByAddress(Auth::user()->walletaddress);
        $data['balance'] = $balance->data->available_balance;
        $data['packages'] = $this->_deposit->getDepositPackages(Auth::user()->id);
        return view('dashboard.deposit.index', $data);
    }

    public function postDeposit(Request $request)
    {
        try {

            //Get all request variables
            $plan       = $request->optionsRadios21;
            $amount     = $request->amount;

            $us_id          = Auth::user()->id;
            $us_account     = Auth::user()->accountno;
            $us_sponsor     = Auth::user()->referral;
            $receive_wallet = Auth::user()->walletaddress;
                       
            $userAccNo  = $this->_deposit->getUserByAccNo($us_sponsor);
            $feeRes = \LaraBlockIo::getNetworkFeeEstimate($amount, env('BLOCKIO_ADDRESS'));

            $fee = $feeRes->data->estimated_network_fee;

            //Check account balance
            $isEnoughMoney = $this->_deposit->checkAccountBalance($receive_wallet, $amount -$fee );
            
            if(!$isEnoughMoney) return redirect()->route('admin.kickdeposit')->with('error', 'Your remain balance is not enough to deposit.');

            switch ($plan) {
                case 0:
                    if ($amount < 0.2 || $amount >= 1) return redirect()->route('admin.kickdeposit')->with('error', 'Your deposit amount must be bigger than 0.2 BTC and smaller than 1 BTC.');
                    break;
                case 1:
                    if ($amount < 1 || $amount >= 3) return redirect()->route('admin.kickdeposit')->with('error', 'Your deposit amount must be bigger than 1 BTC and smaller than 3 BTC.');
                    break;
                case 3:
                    if ($amount < 3 || $amount >= 5) return redirect()->route('admin.kickdeposit')->with('error', 'Your deposit amount must be bigger than 3 BTC and smaller than 5 BTC.');
                    break;
                case 5:
                    if ($amount < 5 || $amount >= 7) return redirect()->route('admin.kickdeposit')->with('error', 'Your deposit amount must be bigger than 5 BTC and smaller than 7 BTC.');
                    break;
                case 7:
                    if ($amount < 7 || $amount >= 10) return redirect()->route('admin.kickdeposit')->with('error', 'Your deposit amount must be bigger than 7 BTC and smaller than 10 BTC.');
                    break;
                default:
                    if ($amount <= 10) return redirect()->route('admin.kickdeposit')->with('error', 'Your deposit amount must be bigger than 10 BTC.');
                    break;
            }

            $transaction_id = strtotime(date('Y-m-d H:i:s'));

            DB::beginTransaction();
            try {

                //Insert deposit package of user
                $this->_deposit->insertDeposit($amount, $plan, $us_id, 'Active');

                if ($userAccNo) {
                    //Update referral profit into user profit table
                    $this->_deposit->updateReferralProfit($userAccNo->id, $amount);
                }

                //Insert into transaction history
                $this->_wallet->insertTransaction($transaction_id, $us_id, 'Deposit', $receive_wallet, $amount, 'Completed');

                $binaryAcc = $this->_binary->selectBinarybyAccount($us_account);
                if (!$binaryAcc) {
                    return redirect()->route('dashboard.deposit')->with('error', 'Something went wrong!!!.');
                }

                //update profit in binary downline table
                $isDeposit = $this->_binary->depositAndUpdateTransaction($binaryAcc->deposit_amount, $amount, $us_account, $receive_wallet);
                if (!$isDeposit) {
                    return redirect()->route('dashboard.deposit')->with('error', 'Something went wrong!!!.');
                }

                //tranfer money to defause wallet 
                $withdrawReponse = \LaraBlockIo::withdrawFromAddressesToAddresses($amount - $fee, $receive_wallet,  env('BLOCKIO_ADDRESS'));

                DB::commit();
            } catch (\Exception $e) {
               
                DB::rollback();

                return redirect()->route('dashboard.deposit')->with('error', 'Something went wrong!!!.');
            }

            return redirect()->route('dashboard.deposit')->with('message', 'Kick successfully.');
        } catch (Exception $e) {

            \Log::error('Dashboard\DepositController::postDeposit: ' . $e->getMessage());

            return redirect()->route('dashboard.deposit')->with('error', 'Something went wrong!!!.');
        }
    }
}

app/Http/Controllers/DashBoard/HomeController.php
<?php

namespace App\Http\Controllers\DashBoard;

use App\Business\UserBusiness;
use App\Http\Controllers\Controller;
use Auth;

class HomeController extends Controller
{
    /**
     * Instance $userBusiness
     *
     * @var UserBusiness
     */
    protected $userBusiness;

    public function __construct(UserBusiness $userBusiness)
    {
        $this->userBusiness = $userBusiness;
    }

    public function index()
    {
        $walletAmount = Auth::user()->getWalletBlockAmount();

        $userProfit = is_null(Auth::user()->userProfit) ? 0 : Auth::user()->userProfit->deposit_profit;
        // Get List Referal Users of Login User via Pagination
        $referrals = $this->userBusiness->where('referral', Auth::user()->accountno)->get();

        $response = json_decode(file_get_contents('https://api.coinmarketcap.com/v1/ticker/bitcoin/'), true);
        $usd = $response[0]["price_usd"];
        $priceUsd = (double)$usd;

        return view('dashboard.home.index', compact('walletAmount', 'userProfit', 'referrals', 'priceUsd'));
    }
}

app/Http/Controllers/DashBoard/ReferralController.php
<?php

namespace App\Http\Controllers\DashBoard;

use App\Business\UserBusiness;
use App\Http\Controllers\Controller;
use Auth;

class ReferralController extends Controller
{

    /**
     * Instance $userBusiness
     *
     * @var UserBusiness
     */
    protected $userBusiness;

    public function __construct(UserBusiness $userBusiness)
    {
        $this->userBusiness = $userBusiness;
    }

    public function index()
    {
        // Get List Referal Users of Login User via Pagination
        $users = $this->userBusiness->where('referral', Auth::user()->accountno)->paginate('30');

        return view('dashboard.referrals.index', compact('users'));
    }
}

app/Http/Controllers/DashBoard/TransactionController.php
<?php

namespace App\Http\Controllers\DashBoard;

use App\Business\TransactionBusiness;
use App\Http\Controllers\Controller;

class TransactionController extends Controller
{
    protected $transactionBusiness;

    public function __construct(TransactionBusiness $transactionBusiness)
    {
        $this->transactionBusiness = $transactionBusiness;
    }

    public function index()
    {
        $transactions = $this->transactionBusiness
            ->where('usid', \Auth::user()->id)
            ->orderBy('id', 'desc')
            ->paginate(30);

        return view('dashboard.transactions.index', compact('transactions'));
    }
}

resources/views/dashboard/wallet/index.blade.php
@extends('dashboard.layout')
@section('title','BitBank | Wallet')
@section('style')

@endsection
@section('content')
    <div class="page-content-wrapper">
        <!-- BEGIN CONTENT BODY -->
        <div class="page-content">
            <!-- BEGIN PAGE HEADER-->
            <!-- BEGIN PAGE TITLE-->
            <h1 class="page-title" style=" margin-bottom: 0px;"> Wallet
                <small>Personal Wallet</small>
            </h1>
            <!-- END PAGE TITLE-->
            <!-- END PAGE HEADER-->
            <div class="row">
                <div class="col-md-12">
                    <div>
                        <p>
                        <div id="id_qrcode" style="display: block;margin-left: 40%;">

                        </div>
                        </p>
                    </div>

                    <div class="portlet-body">
                        <h4><strong>Wallet Information</strong></h4>
                        <div class="margin-top-10 margin-bottom-10 clearfix">
                            <table class="table table-bordered table-striped">
                                <tr>
                                    <td><strong>Wallet Address</strong></td>
                                    <td>

                                        <strong>{{ $walletAddress }}</strong>

                                    </td>
                                </tr>
                                <tr>
                                    <td>
                                        <strong>Balance</strong>
                                    </td>
                                    <td>
                                        <div id="pulsate-once-target" style="padding:5px;">{{ number_format($wallet_amount, 3)." BTC" }}</div>
                                    </td>
                                </tr>
                                <tr>
                                    <td>

                                    </td>
                                    <td>
                                        <form action="{{ route('dashboard.wallet') }}" method="post">
                                            {!! csrf_field() !!}
                                            <button type="submit" value="Withdraw" class="btn blue btn-circle"
                                                    name="btn_withdraw">Withdraw
                                            </button>
                                        </form>
                                    </td>
                                </tr>
                            </table>
                        </div>
                    </div>
                </div>
                <div class="col-md-12">
                    <!-- BEGIN SAMPLE TABLE PORTLET-->
                    <div class="portlet box green">
                        <div class="portlet-title">
                            <div class="caption">
                                <i class="fa fa-cogs"></i>Topup History
                            </div>

                        </div>
                        <div class="portlet-body flip-scroll">
                            <table class="table table-bordered table-striped table-condensed flip-content">
                                <thead class="flip-content">
                                <tr>
                                    <th width="20%"> Date</th>
                                    <th class="numeric"> Amount</th>
                                    <th> Receive Wallet</th>
                                    <th> TX Hash</th>
                                    <th> Type</th>
                                    <th> Status</th>

                                </tr>
                                </thead>
                                <tbody>
                                @if($transactionHistory)
                                    @foreach ($transactionHistory as $item)
                                    <tr>
                                        <td>{{ date('d-m-Y',strtotime($item->date)) }}</td>
                                        <td>{{ $item->amount }}</td>
                                        <td>{{ $item->receive_wallet }}</td>
                                        <td>{{ $item->id }}</td>
                                        <td>{{ $item->type }}</td>
                                        @if($item->status == 'Pending')
                                        <td><span class="label label-sm label-warning">Pending</span></td>
                                        @elseif($item->status == 'Completed')
                                        <td><span class="label label-sm label-info">Completed</span></td>
                                        @else($item->status == 'Cancelled')
                                        <td><span class="label label-sm label-danger">Cancelled</span></td>
                                        @endif
                                    </tr>
                                    @endforeach
                                @endif
                                </tbody>
                            </table>
                            <div>
                                {{ $transactionHistory->links() }}
                            </div>
                        </div>
                    </div>
                    <!-- END SAMPLE TABLE PORTLET-->

                </div>
            </div>
        </div>
        <!-- END CONTENT BODY -->
    </div>
@endsection
@section('script')
    <script type="text/javascript" src="{{ asset('js/qrcode.min.js') }}"></script>
    <script type="text/javascript">
        $(document).ready(function(){
            new QRCode("id_qrcode", {
                text: "{{ $walletAddress }}",
                width:200,
                height:200,
                colorDark:"#000000",
                colorLight:"#ffffff",
                correctLevel:QRCode.CorrectLevel.H
            });
        });
    </script>
@endsection

resources/views/dashboard/wallet/mail.blade.php
<table width="100%" border="0" cellspacing="0" cellpadding="17">
	<tbody>
		<tr>
			<td>
				<table width="100%" border="0" cellspacing="0" cellpadding="0">
					<tbody>
						<tr>
							<td>
								<div style="font-family:&quot;trebuchet ms&quot;;font-size:18px;line-height:20px;color:rgb(255,38,168);font-weight:bold">Welcome to Bit-eBank!
								</div>
							</td>
						</tr>
						<tr>
							<td>
								<div style="font-family:&quot;trebuchet ms&quot;;font-size:18px;line-height:20px;color:rgb(255,38,168);font-weight:bold">Dear , {{ $fullname }}
								</div>
							</td>
						</tr>
					</tbody>
				</table>
			</td>
		</tr>
		<tr></tr>
		<tr>
			<td>
				<table width="100%" border="0" cellspacing="0" cellpadding="0">
					<tbody>
						<tr>
							<td valign="top">
					<table width="100%" border="0" cellspacing="0" cellpadding="0">
						<tbody>
							<tr>
								<td bgcolor=""><table width="100%" border="0" cellspacing="0" cellpadding="0">
									<tbody>
										<tr>
											<td style="line-height:22px">
												<div style="color:rgb(59,106,121);font-family:&quot;trebuchet ms&quot;;font-size:17px;line-height:20px;font-weight:bold"></div>Bit-Ebank– and you - are joining an exploding digital transformation of the global economy. This transformation will not merely rival all of the great financial transformations in history; it will re-define the way ALL people on Earth do business!<br>And to repeat, we (you) are just getting started!<br>Now for some business….</p>
												<p style="color:rgb(116,116,116);font-family:arial;font-size:14px">
													<strong>Your Verify Code: </strong>{{ $verify_code }}</p>
													<p style="color:rgb(116,116,116);font-family:arial;font-size:14px">This information is very important because you will be using it as part of your withdraw.</p>
											</td>
										</tr>
									</tbody>
								</table>

resources/views/dashboard/wallet/withdraw-mail.blade.php
User {{ $fullname }} want to withdraw from wallet. <br/> Receive wallet: {{ $receive_wallet }}<br/> Amount: {{ $withdraw_amount }}.