routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
/**
 * AUTHENTICATION
 */
Route::group(['prefix' => '/', 'as' => 'auth.'], function () {

    /**
     * Middleware Guest
     */
    Route::middleware(['guest'])->group(function () {
        // Login
        Route::get('/login', 'Auth\LoginController@showLoginForm')->name('login.form');
        Route::post('/login', 'Auth\LoginController@login')->name('login.post');

        // Forgot
        Route::get('/forgot', 'Auth\ForgotPasswordController@index')->name('forgot');
        Route::post('/forgot', 'Auth\ForgotPasswordController@sendEmail')->name('forgot.send');
        Route::get('/forgot/verify/{token}', 'Auth\ForgotPasswordController@verifyMail')->name('forgot.verify');
    });
    Route::middleware(['auth'])->group(function () {
        Route::get('/register/{accountno?}/{leg?}', 'Auth\RegisterController@showRegistrationForm')->name('register.form');
        Route::post('/register', 'Auth\RegisterController@register')->name('register.post');
    });

    // Logout
    Route::post('/logout', 'Auth\LoginController@logout')->name('logout')->middleware('auth');
});


/**
 * FRONT PAGE
 */
Route::group(['prefix' => '/', 'as' => 'front.'], function () {

    // Home
    Route::get('/', function () {
        return view('front.home.index');
    })->name('home');

    // Investment
    Route::get('/investment', function () {
        return view('front.investment.index');
    })->name('investment');

    // About
    Route::get('/about', function () {
        return view('front.about.index');
    })->name('about');

    // Faq
    Route::get('/faq', function () {
        return view('front.faq.index');
    })->name('faq');

    // Contact
    Route::get('/contact', function () {
        return view('front.contact.index');
    })->name('contact');

    // Tems
    Route::get('/tems', function () {
        return view('front.tems.index');
    })->name('tems');
});

/**
 * Auth Middleware Group
 */
Route::middleware(['auth'])->group(function () {
    /**
     * DASHBOARD PAGE
     */
    Route::group(['prefix' => '/dashboard', 'as' => 'dashboard.','middleware' => 'user'], function () {

        // Home
        Route::get('/', 'DashBoard\HomeController@index')->name('home');

        // Wallet
        Route::get('/wallet', 'DashBoard\WalletController@index')->name('wallet');
        Route::post('/wallet', 'DashBoard\WalletController@handleWithdraw')->name('wallet');
        Route::get('/withdraw', 'DashBoard\WalletController@getWithdraw')->name('withdraw');
        Route::post('/withdraw', 'DashBoard\WalletController@postWithdraw')->name('withdraw');

        // Wallet
        Route::get('/referrals', 'DashBoard\ReferralController@index')->name('referrals');

        // Binary
        Route::get('/binary/{accountno?}', 'DashBoard\BinaryController@index')->name('binary');

        // Transactions
        Route::get('/transactions', 'DashBoard\TransactionController@index')->name('transactions');

        Route::get('/deposit', 'DashBoard\DepositController@deposit')->name('deposit');
        Route::post('/deposit', 'DashBoard\DepositController@postDeposit')->name('deposit');

        // Commission
        Route::get('/commission', 'DashBoard\CommissionController@index')->name('commission.index');
        Route::post('/commission/email', 'DashBoard\CommissionController@handleEmail')->name('commission.email');
        Route::get('/commission/withdraw', 'DashBoard\CommissionController@getCommission')->name('commission');
        Route::post('/commission/withdraw', 'DashBoard\CommissionController@postCommission')->name('commission');
        Route::get('/commission/binary', 'DashBoard\CommissionController@getBinary')->name('binary.commission');
        Route::post('/commission/binary', 'DashBoard\CommissionController@postBinary')->name('binary.commission');
        Route::get('/monthly/withdraw', 'DashBoard\CommissionController@getMonthly')->name('monthly');
        Route::post('/monthly/withdraw', 'DashBoard\CommissionController@postMonthly')->name('monthly');

        // User
        Route::group(['prefix' => '/user', 'as' => 'user.'], function () {
            Route::get('/overview', 'DashBoard\UserController@overview')->name('overview');

            // Profile
            Route::get('/profile', 'DashBoard\UserController@profile')->name('profile');
            Route::put('/profile', 'DashBoard\UserController@updateProfile')->name('profile.update');
            Route::put('/profile/password', 'DashBoard\UserController@updatePassword')->name('profile.password');
        });

        // Contact
        Route::get('/contact', 'DashBoard\ContactController@index')->name('contact');
        Route::post('/contact', 'DashBoard\ContactController@sendMail')->name('contact.send');

        // Calendar
        Route::get('/calendar', function () {
            return view('dashboard.calendar.index');
        })->name('calendar');

    });

    /**
     * ADMIN PAGE
     */
    Route::group(['prefix' => '/admin', 'as' => 'admin.','middleware' => 'admin'], function () {
        // Home
        Route::get('/', function () {
            return view('admin.home.index');
        })->name('home');

        Route::get('/kickdeposit', 'Admin\DepositController@deposit')->name('kickdeposit');
        Route::post('/kickdeposit', 'Admin\DepositController@postDeposit')->name('kickdeposit');

        Route::get('/countprofit/monthly', 'Admin\ProfitMonthlyController@index')->name('countprofit');

        // Pay
        Route::group(['prefix' => '/pay', 'as' => 'pay.'], function () {

            Route::get('/profit', 'Admin\PaymentController@profit')->name('profit');
            Route::post('/profit/{id}', 'Admin\PaymentController@withdrawProfit')->name('profit.withdraw');

            Route::get('/interest', 'Admin\PaymentController@interest')->name('interest');
            Route::post('/interest/{id}', 'Admin\PaymentController@payInterest')->name('interest.withdraw');

            Route::get('/wallet', 'Admin\PaymentController@wallet')->name('wallet');
            Route::post('/wallet/{id}', 'Admin\PaymentController@withdrawWallet')->name('wallet.withdraw');
        });

        Route::get('/binary', 'Admin\BinaryController@index')->name('binary');
        Route::post('/binary/{id}', 'Admin\BinaryController@payment')->name('binary.payment');

        // ADmin
        Route::group(['prefix' => '/user', 'as' => 'user.'], function () {
            Route::get('/overview', 'Admin\UserController@overview')->name('overview');

            // Profile
            Route::get('/profile', 'Admin\UserController@profile')->name('profile');
            Route::put('/profile', 'Admin\UserController@updateProfile')->name('profile.update');
            Route::put('/profile/password', 'Admin\UserController@updatePassword')->name('profile.password');
        });

        Route::get('/transfer', 'Admin\TransferController@getTransfer')->name('transfer');
        Route::post('/transfer', 'Admin\TransferController@postTransfer')->name('transfer');
    });
});

app/Http/Controllers/Admin/BinaryController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Business\BinaryTempBusiness;
use App\Business\TransactionBusiness;
use App\Business\UserBusiness;
use App\Business\UserProfitBusiness;
use App\Http\Controllers\Controller;
use Carbon\Carbon;
use Illuminate\Http\Request;

class BinaryController extends Controller
{
    protected $userBusiness;

    protected $binaryTempBusiness;

    protected $transactionBusiness;

    protected $userProfitBusiness;

    /**
     * BinaryController constructor.
     *
     * @param UserBusiness $userBusiness
     * @param BinaryTempBusiness $binaryTempBusiness
     * @param TransactionBusiness $transactionBusiness
     * @param UserProfitBusiness $userProfitBusiness
     */
    public function __construct(UserBusiness $userBusiness,
                                BinaryTempBusiness $binaryTempBusiness,
                                TransactionBusiness $transactionBusiness,
                                UserProfitBusiness $userProfitBusiness)
    {
        $this->userBusiness = $userBusiness;
        $this->binaryTempBusiness = $binaryTempBusiness;
        $this->transactionBusiness = $transactionBusiness;
        $this->userProfitBusiness = $userProfitBusiness;
    }

    public function index()
    {
        $users = $this->userBusiness->getList('30');

        return view('admin.binary.profit', compact('users'));
    }

    /**
     * Payment Method
     *
     * @param Request $request
     *
     * @return \Response
     */
    public function payment(Request $request)
    {
        try {
            \DB::beginTransaction();
            $this->userProfitBusiness->update($request->input('user_id'), $request->input('payamount'));

            $this->transactionBusiness->insert($request->input('user_id'), $request->input('payamount'), 'Binary Profit');
            $this->binaryTempBusiness->updateOrCreate([
                'accountno' => $request->input('accountno')
            ], [
                'last_left_venue'   => $request->input('leftdeposit'),
                'last_right_venue'  => $request->input('rightdeposit'),
                'last_date_payment' => Carbon::today()->timestamp
            ]);
            \DB::commit();

            return redirect()->route('admin.binary')->with([
                'status'  => 'success',
                'message' => 'Your profit paid!!!'
            ]);
        } catch (\Exception $e) {
            \Log::error('Admin\BinaryController::payment : ' . $e->getMessage());
            \DB::rollBack();

            return redirect()->route('admin.binary')->with([
                'status'  => 'danger',
                'message' => 'Something went wrong!!!!'
            ]);
        }
    }
}

app/Http/Controllers/DashBoard/BinaryController.php
<?php

namespace App\Http\Controllers\DashBoard;

use App\Business\BinaryDownlineBusiness;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Auth;

class BinaryController extends Controller
{
    /**
     * Instance $binaryDownlineBusiness
     *
     * @var BinaryDownlineBusiness
     */
    protected $binaryDownlineBusiness;

    /**
     * BinaryController constructor.
     *
     * @param BinaryDownlineBusiness $binaryDownlineBusiness
     */
    public function __construct(BinaryDownlineBusiness $binaryDownlineBusiness)
    {
        $this->binaryDownlineBusiness = $binaryDownlineBusiness;
    }

    public function index($accountno = null)
    {

        // Get Current User Id by Request
        if (is_null($accountno)) {
            $accountno = Auth::user()->accountno;
        }

        // Get Current Users List;
        $curUsers = $this->binaryDownlineBusiness->where('accountno', $accountno)->get();

        // Level of Tree
        $level = 4;

        return view('dashboard.binary.index', compact('curUsers', 'level'));

    }
}

app/Http/Controllers/DashBoard/ContactController.php
<?php

namespace App\Http\Controllers\DashBoard;

use App\Http\Controllers\Controller;
use App\Http\Requests\DashBoard\ContactRequest;
use App\Mail\ContactEmail;

class ContactController extends Controller
{
    public function index()
    {
        return view('dashboard.contact.index');
    }

    /**
     * Send Mail Method
     *
     * @param ContactRequest $request
     *
     * @return \Response
     */
    public function sendMail(ContactRequest $request)
    {
        try {
            $contactEmail = collect([
                'name'    => $request->input('name'),
                'email'   => $request->input('email'),
                'ccno'    => $request->input('ccno'),
                'message' => $request->input('message')
            ]);
            \Mail::to(env('MAIL_USERNAME'))->send(new ContactEmail($contactEmail));

            return redirect()->route('dashboard.contact')->with([
                'status'  => 'success',
                'message' => 'Your message was sent!!!'
            ]);
        } catch (\Exception $e) {
            \Log::error('DashBoard\ContactController::sendMail : ' . $e->getMessage());

            return redirect()->route('dashboard.contact')->with([
                'status'  => 'danger',
                'message' => 'Something went wrong!!!!'
            ]);
        }
    }
}

app/Http/Controllers/DashBoard/HomeController.php
<?php

namespace App\Http\Controllers\DashBoard;

use App\Business\UserBusiness;
use App\Http\Controllers\Controller;
use Auth;

class HomeController extends Controller
{
    /**
     * Instance $userBusiness
     *
     * @var UserBusiness
     */
    protected $userBusiness;

    public function __construct(UserBusiness $userBusiness)
    {
        $this->userBusiness = $userBusiness;
    }

    public function index()
    {
        $walletAmount = Auth::user()->getWalletBlockAmount();

        $userProfit = is_null(Auth::user()->userProfit) ? 0 : Auth::user()->userProfit->deposit_profit;
        // Get List Referal Users of Login User via Pagination
        $referrals = $this->userBusiness->where('referral', Auth::user()->accountno)->get();

        $response = json_decode(file_get_contents('https://api.coinmarketcap.com/v1/ticker/bitcoin/'), true);
        $usd = $response[0]["price_usd"];
        $priceUsd = (double)$usd;

        return view('dashboard.home.index', compact('walletAmount', 'userProfit', 'referrals', 'priceUsd'));
    }
}

app/Http/Controllers/DashBoard/ReferralController.php
<?php

namespace App\Http\Controllers\DashBoard;

use App\Business\UserBusiness;
use App\Http\Controllers\Controller;
use Auth;

class ReferralController extends Controller
{

    /**
     * Instance $userBusiness
     *
     * @var UserBusiness
     */
    protected $userBusiness;

    public function __construct(UserBusiness $userBusiness)
    {
        $this->userBusiness = $userBusiness;
    }

    public function index()
    {
        // Get List Referal Users of Login User via Pagination
        $users = $this->userBusiness->where('referral', Auth::user()->accountno)->paginate('30');

        return view('dashboard.referrals.index', compact('users'));
    }
}

app/Http/Controllers/DashBoard/TransactionController.php
<?php

namespace App\Http\Controllers\DashBoard;

use App\Business\TransactionBusiness;
use App\Http\Controllers\Controller;

class TransactionController extends Controller
{
    protected $transactionBusiness;

    public function __construct(TransactionBusiness $transactionBusiness)
    {
        $this->transactionBusiness = $transactionBusiness;
    }

    public function index()
    {
        $transactions = $this->transactionBusiness
            ->where('usid', \Auth::user()->id)
            ->orderBy('id', 'desc')
            ->paginate(30);

        return view('dashboard.transactions.index', compact('transactions'));
    }
}

resources/views/dashboard/binary/index.blade.php
@extends('dashboard.layout')
@section('title','BitBank | Binary')
@section('style')
    <link href="{{ asset('css/family_tree.css') }}" rel="stylesheet" type="text/css">
@endsection
@section('content')
    <div class="page-content-wrapper">
        <!-- BEGIN CONTENT BODY -->
        <div class="page-content">
            <!-- BEGIN PAGE HEADER-->
            <div class="row">
                <div class="col-md-12">
                    <div class="portlet-body">
                        <ul class="nav nav-tabs">
                            <li class="active">
                                <a href="#tab_1_1" data-toggle="tab" aria-expanded="true"> Binary Tree </a>
                            </li>
                            <li class="">
                                <a href="#tab_1_2" data-toggle="tab" aria-expanded="false"> Summary </a>
                            </li>

                        </ul>
                        <div class="tab-content">
                            <div class="tab-pane fade active in" id="tab_1_1"
                                 style="width: 1100px; height: 600px; background-color: white;">

                                <div class="tree" style="overflow-x:scroll;">
                                    @include('dashboard.binary.recursive',compact('curUsers','level'))
                                </div>
                            </div>
                            <div class="tab-pane fade" id="tab_1_2">
                                <!-- BEGIN SAMPLE TABLE PORTLET-->
                                @php
                                    /** @var $curUser \App\Models\BinaryDownline */
                                    $curUser = $curUsers->first();
                                @endphp
                                <div class="col-md-6">
                                    <div class="portlet box green">
                                        <div class="portlet-title">
                                            <div class="caption">
                                                LEFT
                                            </div>
                                            <div class="tools">
                                                <p>Total: {{ empty($curUser) ? 0 : $curUser->getLeftDeposit() }} BTC</p>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <!-- BEGIN CONDENSED TABLE PORTLET-->
                                    <div class="portlet box red">
                                        <div class="portlet-title">
                                            <div class="caption">
                                                <i class="fa fa-picture"></i>RIGHT
                                            </div>
                                            <div class="tools">
                                                <p>Total: {{ empty($curUser) ? 0 : $curUser->getRightDeposit() }} BTC</p>
                                            </div>
                                        </div>
                                    </div>
                                    <!-- END CONDENSED TABLE PORTLET-->
                                </div>
                            </div>

                        </div>
                    </div>

                </div>
            </div>
        </div>
        <!-- END CONTENT BODY -->
    </div>
@endsection

resources/views/dashboard/binary/recursive.blade.php
@if ($level > 0)
    @php($level--)
    <ul>
        @foreach($curUsers as $key => $curUser)
            @if(is_null($curUsers->get($key)))
                <li>
                    <a href="{{ route('auth.register.form',['accountno' => $accountno, 'leg' => $key]) }}">Add new
                        member</a>
                </li>
            @else

                <li>
                    <a href="{{ route('dashboard.binary',['accountno' => $curUser->accountno]) }}">
                        <p><strong>{{ $curUser->name }}</strong></p>
                        {{ $curUser->accountno }}
                    </a>
                    @if ($level > 0)
                        @include('dashboard.binary.recursive',[
                            'curUsers'  => $curUser->getBinaryTree(),
                            'level'     => $level,
                            'accountno' => $curUser->accountno
                        ])
                    @endif
                </li>
            @endif
        @endforeach
    </ul>
@endif