routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
/**
 * AUTHENTICATION
 */
Route::group(['prefix' => '/', 'as' => 'auth.'], function () {

    /**
     * Middleware Guest
     */
    Route::middleware(['guest'])->group(function () {
        // Login
        Route::get('/login', 'Auth\LoginController@showLoginForm')->name('login.form');
        Route::post('/login', 'Auth\LoginController@login')->name('login.post');

        // Forgot
        Route::get('/forgot', 'Auth\ForgotPasswordController@index')->name('forgot');
        Route::post('/forgot', 'Auth\ForgotPasswordController@sendEmail')->name('forgot.send');
        Route::get('/forgot/verify/{token}', 'Auth\ForgotPasswordController@verifyMail')->name('forgot.verify');
    });
    Route::middleware(['auth'])->group(function () {
        Route::get('/register/{accountno?}/{leg?}', 'Auth\RegisterController@showRegistrationForm')->name('register.form');
        Route::post('/register', 'Auth\RegisterController@register')->name('register.post');
    });

    // Logout
    Route::post('/logout', 'Auth\LoginController@logout')->name('logout')->middleware('auth');
});


/**
 * FRONT PAGE
 */
Route::group(['prefix' => '/', 'as' => 'front.'], function () {

    // Home
    Route::get('/', function () {
        return view('front.home.index');
    })->name('home');

    // Investment
    Route::get('/investment', function () {
        return view('front.investment.index');
    })->name('investment');

    // About
    Route::get('/about', function () {
        return view('front.about.index');
    })->name('about');

    // Faq
    Route::get('/faq', function () {
        return view('front.faq.index');
    })->name('faq');

    // Contact
    Route::get('/contact', function () {
        return view('front.contact.index');
    })->name('contact');

    // Tems
    Route::get('/tems', function () {
        return view('front.tems.index');
    })->name('tems');
});

/**
 * Auth Middleware Group
 */
Route::middleware(['auth'])->group(function () {
    /**
     * DASHBOARD PAGE
     */
    Route::group(['prefix' => '/dashboard', 'as' => 'dashboard.','middleware' => 'user'], function () {

        // Home
        Route::get('/', 'DashBoard\HomeController@index')->name('home');

        // Wallet
        Route::get('/wallet', 'DashBoard\WalletController@index')->name('wallet');
        Route::post('/wallet', 'DashBoard\WalletController@handleWithdraw')->name('wallet');
        Route::get('/withdraw', 'DashBoard\WalletController@getWithdraw')->name('withdraw');
        Route::post('/withdraw', 'DashBoard\WalletController@postWithdraw')->name('withdraw');

        // Wallet
        Route::get('/referrals', 'DashBoard\ReferralController@index')->name('referrals');

        // Binary
        Route::get('/binary/{accountno?}', 'DashBoard\BinaryController@index')->name('binary');

        // Transactions
        Route::get('/transactions', 'DashBoard\TransactionController@index')->name('transactions');

        Route::get('/deposit', 'DashBoard\DepositController@deposit')->name('deposit');
        Route::post('/deposit', 'DashBoard\DepositController@postDeposit')->name('deposit');

        // Commission
        Route::get('/commission', 'DashBoard\CommissionController@index')->name('commission.index');
        Route::post('/commission/email', 'DashBoard\CommissionController@handleEmail')->name('commission.email');
        Route::get('/commission/withdraw', 'DashBoard\CommissionController@getCommission')->name('commission');
        Route::post('/commission/withdraw', 'DashBoard\CommissionController@postCommission')->name('commission');
        Route::get('/commission/binary', 'DashBoard\CommissionController@getBinary')->name('binary.commission');
        Route::post('/commission/binary', 'DashBoard\CommissionController@postBinary')->name('binary.commission');
        Route::get('/monthly/withdraw', 'DashBoard\CommissionController@getMonthly')->name('monthly');
        Route::post('/monthly/withdraw', 'DashBoard\CommissionController@postMonthly')->name('monthly');

        // User
        Route::group(['prefix' => '/user', 'as' => 'user.'], function () {
            Route::get('/overview', 'DashBoard\UserController@overview')->name('overview');

            // Profile
            Route::get('/profile', 'DashBoard\UserController@profile')->name('profile');
            Route::put('/profile', 'DashBoard\UserController@updateProfile')->name('profile.update');
            Route::put('/profile/password', 'DashBoard\UserController@updatePassword')->name('profile.password');
        });

        // Contact
        Route::get('/contact', 'DashBoard\ContactController@index')->name('contact');
        Route::post('/contact', 'DashBoard\ContactController@sendMail')->name('contact.send');

        // Calendar
        Route::get('/calendar', function () {
            return view('dashboard.calendar.index');
        })->name('calendar');

    });

    /**
     * ADMIN PAGE
     */
    Route::group(['prefix' => '/admin', 'as' => 'admin.','middleware' => 'admin'], function () {
        // Home
        Route::get('/', function () {
            return view('admin.home.index');
        })->name('home');

        Route::get('/kickdeposit', 'Admin\DepositController@deposit')->name('kickdeposit');
        Route::post('/kickdeposit', 'Admin\DepositController@postDeposit')->name('kickdeposit');

        Route::get('/countprofit/monthly', 'Admin\ProfitMonthlyController@index')->name('countprofit');

        // Pay
        Route::group(['prefix' => '/pay', 'as' => 'pay.'], function () {

            Route::get('/profit', 'Admin\PaymentController@profit')->name('profit');
            Route::post('/profit/{id}', 'Admin\PaymentController@withdrawProfit')->name('profit.withdraw');

            Route::get('/interest', 'Admin\PaymentController@interest')->name('interest');
            Route::post('/interest/{id}', 'Admin\PaymentController@payInterest')->name('interest.withdraw');

            Route::get('/wallet', 'Admin\PaymentController@wallet')->name('wallet');
            Route::post('/wallet/{id}', 'Admin\PaymentController@withdrawWallet')->name('wallet.withdraw');
        });

        Route::get('/binary', 'Admin\BinaryController@index')->name('binary');
        Route::post('/binary/{id}', 'Admin\BinaryController@payment')->name('binary.payment');

        // ADmin
        Route::group(['prefix' => '/user', 'as' => 'user.'], function () {
            Route::get('/overview', 'Admin\UserController@overview')->name('overview');

            // Profile
            Route::get('/profile', 'Admin\UserController@profile')->name('profile');
            Route::put('/profile', 'Admin\UserController@updateProfile')->name('profile.update');
            Route::put('/profile/password', 'Admin\UserController@updatePassword')->name('profile.password');
        });

        Route::get('/transfer', 'Admin\TransferController@getTransfer')->name('transfer');
        Route::post('/transfer', 'Admin\TransferController@postTransfer')->name('transfer');
    });
});

resources/views/admin/elements/footer.blade.php
<div class="page-footer">
    <div class="page-footer-inner"> 2015 &copy; Singapore National Bank
    </div>
    <div class="scroll-to-top">
        <i class="icon-arrow-up"></i>
    </div>
</div>

resources/views/admin/elements/header.blade.php
<div class="page-header navbar navbar-fixed-top">
    <!-- BEGIN HEADER INNER -->
    <div class="page-header-inner ">
        <!-- BEGIN LOGO -->
        <div class="page-logo">
            <a href="{{ route('admin.home') }}">
                <img src="{{ asset('assets/layouts/layout/img/logo.png') }}" alt="logo" class="logo-default"/> </a>
            <div class="menu-toggler sidebar-toggler">
                <span></span>
            </div>
        </div>
        <!-- END LOGO -->
        <!-- BEGIN RESPONSIVE MENU TOGGLER -->
        <a href="javascript:;" class="menu-toggler responsive-toggler" data-toggle="collapse"
           data-target=".navbar-collapse">
            <span></span>
        </a>
        <!-- END RESPONSIVE MENU TOGGLER -->
        <!-- BEGIN TOP NAVIGATION MENU -->
        <div class="top-menu">
            <ul class="nav navbar-nav pull-right">
                <!-- BEGIN USER LOGIN DROPDOWN -->
                <li class="dropdown dropdown-user">
                    <a href="javascript:;" class="dropdown-toggle" data-toggle="dropdown" data-hover="dropdown"
                       data-close-others="true">
                        <img alt="" class="img-circle" src="{{ asset('assets/layouts/layout/img/avatar.png') }}"/>
                        <span class="username username-hide-on-mobile">{{ Auth::user()->getFullName() }}</span>
                        <i class="fa fa-angle-down"></i>
                    </a>
                    <ul class="dropdown-menu dropdown-menu-default">
                        <li>
                            <a href="{{ route('admin.user.profile') }}">
                                <i class="icon-user"></i> My Profile </a>
                        </li>
                        <li>
                            <a href="{{ route('auth.logout') }}"
                               onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                <i class="icon-key"></i> Log Out
                            </a>

                            <form id="logout-form" action="{{ route('auth.logout') }}" method="POST"
                                  style="display: none;">
                                {{ csrf_field() }}
                            </form>
                        </li>
                    </ul>
                </li>
                <!-- END USER LOGIN DROPDOWN -->


            </ul>
        </div>
        <!-- END TOP NAVIGATION MENU -->
    </div>
    <!-- END HEADER INNER -->
</div>

resources/views/admin/elements/sidebar.blade.php
<div class="page-sidebar-wrapper">
    <!-- BEGIN SIDEBAR -->
    <div class="page-sidebar navbar-collapse collapse">
        <!-- BEGIN SIDEBAR MENU -->
        <ul class="page-sidebar-menu  page-header-fixed" data-keep-expanded="false" data-auto-scroll="true"
            data-slide-speed="200" style="padding-top: 20px">
            <!-- BEGIN SIDEBAR TOGGLER BUTTON -->
            <li class="sidebar-toggler-wrapper hide">
                <div class="sidebar-toggler">
                    <span></span>
                </div>
            </li>
            <!-- END SIDEBAR TOGGLER BUTTON -->
            <li class="nav-item {{ Request::is('admin') ? 'open active' : '' }}">
                <a href="{{ route('admin.home') }}" class="nav-link nav-toggle">
                    <i class="icon-home"></i>
                    <span class="title" href="personal.php">Admin Page</span>
                    @if(Request::is('admin'))
                        <span class="selected"></span>
                        <span class="arrow open"></span>
                    @else
                        <span class="arrow"></span>
                    @endif
                </a>

            </li>
            <li class="heading">
                <h3 class="uppercase">Features</h3>
            </li>
            <li class="nav-item {{ Request::is('admin/kickdeposit') ? 'open active' : '' }}">
                <a href="{{ route('admin.kickdeposit') }}" class="nav-link nav-toggle">
                    <i class="icon-size-actual"></i>
                    <span class="title">Kick Deposit</span>
                    @if(Request::is('admin/kickdeposit'))
                        <span class="selected"></span>
                        <span class="arrow open"></span>
                    @else
                        <span class="arrow"></span>
                    @endif
                </a>
            </li>

            <li class="nav-item {{ Request::is('admin/countprofit/monthly') ? 'open active' : '' }}">
                <a href="{{ route('admin.countprofit') }}" class="nav-link nav-toggle">
                    <i class="icon-calculator"></i>
                    <span class="title">Count Profit Monthly</span>
                    @if(Request::is('admin/countprofit/monthly'))
                        <span class="selected"></span>
                        <span class="arrow open"></span>
                    @else
                        <span class="arrow"></span>
                    @endif
                </a>
            </li>

            <li class="nav-item {{ Request::is('admin/pay*') ? 'open active' : '' }}">
                <a href="javascript:;" class="nav-link nav-toggle">
                    <i class="icon-share-alt"></i>
                    <span class="title">Pay</span>
                    @if(Request::is('admin/pay*'))
                        <span class="selected"></span>
                        <span class="arrow open"></span>
                    @else
                        <span class="arrow"></span>
                    @endif
                </a>
                <ul class="sub-menu">
                    <li class="nav-item  {{ Request::is('admin/pay/interest') ? 'open active' : '' }}">
                        <a href="{{ route('admin.pay.interest') }}" class="nav-link ">
                            <i class="icon-bar-chart"></i>
                            <span class="title">Interest</span>
                            @if(Request::is('admin/pay/interest'))
                                <span class="selected"></span>
                                <span class="arrow open"></span>
                            @else
                                <span class="arrow"></span>
                            @endif
                        </a>
                    </li>
                    <li class="nav-item  {{ Request::is('admin/pay/profit') ? 'open active' : '' }}">
                        <a href="{{ route('admin.pay.profit') }}" class="nav-link ">
                            <i class="icon-bar-chart"></i>
                            <span class="title">Profit</span>
                            @if(Request::is('admin/pay/profit'))
                                <span class="selected"></span>
                                <span class="arrow open"></span>
                            @else
                                <span class="arrow"></span>
                            @endif
                        </a>
                    </li>
                    <li class="nav-item  {{ Request::is('admin/pay/wallet') ? 'open active' : '' }}">
                        <a href="{{ route('admin.pay.wallet') }}" class="nav-link ">
                            <i class="icon-wallet"></i>
                            <span class="title">Wallet</span>
                            @if(Request::is('admin/pay/wallet'))
                                <span class="selected"></span>
                                <span class="arrow open"></span>
                            @else
                                <span class="arrow"></span>
                            @endif
                        </a>
                    </li>
                </ul>
            </li>

            <li class="nav-item {{ Request::is('admin/binary') ? 'open active' : '' }}">
                <a href="{{ route('admin.binary') }}" class="nav-link nav-toggle">
                    <i class="icon-bubbles"></i>
                    <span class="title">Binary</span>
                    @if(Request::is('admin/binary'))
                        <span class="selected"></span>
                        <span class="arrow open"></span>
                    @else
                        <span class="arrow"></span>
                    @endif
                </a>
            </li>
            
            <li class="nav-item {{ Request::is('admin/transfer') ? 'open active' : '' }}">
                <a href="{{ route('admin.transfer') }}" class="nav-link nav-toggle">
                    <i class="glyphicon glyphicon-transfer"></i>
                    <span class="title">Personal Withdraw</span>
                    @if(Request::is('admin/binary'))
                        <span class="selected"></span>
                        <span class="arrow open"></span>
                    @else
                        <span class="arrow"></span>
                    @endif
                </a>
            </li>

            <li class="heading">
                <h3 class="uppercase">Admin Profile</h3>
            </li>

            <li class="nav-item {{ Request::is('admin/user*') ? 'open active' : '' }}">
                <a href="javascript:;" class="nav-link nav-toggle">
                    <i class="icon-user"></i>
                    <span class="title">Admin</span>
                    @if(Request::is('admin/user*'))
                        <span class="selected"></span>
                        <span class="arrow open"></span>
                    @else
                        <span class="arrow"></span>
                    @endif
                </a>
                <ul class="sub-menu">
                    <li class="nav-item  {{ Request::is('admin/user/overview') ? 'open active' : '' }}">
                        <a href="{{ route('admin.user.overview') }}" class="nav-link ">
                            <i class="icon-user"></i>
                            <span class="title">Overview</span>
                            @if(Request::is('admin/user/overview'))
                                <span class="selected"></span>
                                <span class="arrow open"></span>
                            @else
                                <span class="arrow"></span>
                            @endif
                        </a>
                    </li>
                    <li class="nav-item  {{ Request::is('admin/user/profile') ? 'open active' : '' }}">
                        <a href="{{ route('admin.user.profile') }}" class="nav-link ">
                            <i class="icon-user-female"></i>
                            <span class="title">Account Setting</span>
                            @if(Request::is('admin/user/profile'))
                                <span class="selected"></span>
                                <span class="arrow open"></span>
                            @else
                                <span class="arrow"></span>
                            @endif
                        </a>
                    </li>

                    <li class="nav-item  ">
                        <a href="{{ route('auth.logout') }}" onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();"
                           class="nav-link nav-toggle">
                            <i class="icon-notebook"></i>
                            <span class="title">Logout</span>
                            <span class="arrow"></span>
                        </a>
                    </li>

                </ul>
            </li>
        </ul>
        <!-- END SIDEBAR MENU -->
    </div>
    <!-- END SIDEBAR -->
</div>